CREATE ROLE "VOLUNTEER" WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

CREATE ROLE "SPECIALIST" WITH
  NOLOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

grant "VOLUNTEER" to "SPECIALIST";

grant usage on schema help to "VOLUNTEER", "SPECIALIST";