export default {
    medical: {
        value: 'MEDICAL',
        text: 'ליווי רפואי',
        noun: 'ליווי ל',
        color: '#ff5f5f',
        icon: 'd-icon-medical',
        isIndoor: false,
        background:'linear-gradient(60deg, #ff9b51, #ff5fc1, #ff8886, #ff5f5f)',
        actionColor: '#207bff',
    },
    shopping: {
        value: 'SHOPPING',
        text: 'ליווי לקניות',
        noun: 'ליווי ל',
        color: '#23f7c4',
        icon: 'd-icon-shopping',
        isIndoor: false,
        background:' linear-gradient(60deg, #a1ffe3, #23f7c4)',
        actionColor: '#207bff',
    },
    socialEscort: {
        value: 'SOCIAL_ESCORT',
        text: 'ליווי חברתי',
        noun: 'יציאה ל',
        color: '#6e47ff',
        icon: 'd-icon-social',
        isIndoor: false,
        background : 'linear-gradient(60deg, #993ef9, #6e47ff)',
        actionColor: '#20eaba',
    },
    repairs: {
        value: 'REPAIRS',
        text: 'תיקונים',
        noun: 'תיקון ',
        color: '#ffeb3b',
        icon: 'd-icon-settings',
        isIndoor: true,
        background:'linear-gradient(60deg, #e6b82d, #ffeb3b)',
        actionColor: '#58dd68',
    },
    instructions: {
        value: 'INSTRUCTIONS',
        text: 'הדרכות ותפעול',
        noun: 'הדרכת ',
        color: '#35a7ff',
        icon: 'fa fa-slideshare',
        isIndoor: true,
        background: 'linear-gradient(60deg, #6067ff, #35a7ff)',
        actionColor: '#ff6f6a',
    },
    bureaucracy: {
        value: 'BUREAUCRACY',
        text: 'סיוע בירוקרטי',
        noun: 'סיוע ב',
        color: '#ff5ca9',
        icon: 'd-icon-contract',
        isIndoor: true,
        background: 'linear-gradient(60deg, #ff6b83, #ff5ca9)',
        actionColor: '#ffb13e',
    },
    clean_organize: {
        value: 'CLEAN_ORGANIZE',
        text: 'סדר וארגון',
        noun: 'סיוע ב',
        color: '#3ce778',
        icon: { class: 'material-icons', content: 'collections_bookmark'},
        isIndoor: true,
        background:'linear-gradient(60deg, #20c659, #3ce778)',
        actionColor: '#efcc33',
    },
    social: {
        value: 'SOCIAL_AT_HOME',
        color: '#6e47ff',
        text: 'חברתי',
        noun: 'ישיבה לקפה',
        icon: 'd-icon-social',
        isIndoor: true,
        background: ' linear-gradient(60deg, #993ef9, #6e47ff)',
        actionColor: '#20eaba',
    },
}