export default {
    medical: {
        value: 'MEDICAL',
        text: 'ליווי רפואי',
        noun: 'ליווי ל',
        color: '#ff5f5f',
        icon: 'icon-doctor-stethoscope',
        isIndoor: false,
    },
    shopping: {
        value: 'SHOPPING',
        text: 'ליווי לקניות',
        noun: 'ליווי ל',
        color: '#23f7c4',
        icon: ' icon-shopping-cart',
        isIndoor: false,
    },
    socialEscort: {
        value: 'SOCIAL_ESCORT',
        text: 'ליווי חברתי',
        noun: 'יציאה ל',
        color: '#6e47ff',
        icon: 'icon-party',
        isIndoor: false,
    },
    repairs: {
        value: 'REPAIRS',
        text: 'תיקונים',
        noun: 'תיקון ',
        color: '#ffeb3b',
        icon: 'icon-settings',
        isIndoor: true,
    },
    instructions: {
        value: 'INSTRUCTIONS',
        text: 'הדרכות ותפעול',
        noun: 'הדרכת ',
        color: '#35a7ff',
        icon: 'fa-slideshare',
        isIndoor: true,
    },
    bureaucracy: {
        value: 'BUREAUCRACY',
        text: 'סיוע בירוקרטי',
        noun: 'סיוע ב',
        color: '#ff5ca9',
        icon: 'icon-contract',
        isIndoor: true,
    },  
    clean_organize: {
        value: 'CLEAN_ORGANIZE',
        text: 'סדר וארגון',
        noun: 'סיוע ב',
        color: '#3ce778',
        icon: 'fa-dolly',
        isIndoor: true,
    },
    social: {
        value: 'SOCIAL_AT_HOME',
        color: '#6e47ff',
        text: 'חברתי',
        noun: 'ישיבה לקפה',
        icon: 'fa-coffee',
        isIndoor: true, 
    },
}